version: '3.8'
services:
  es01:
    image: elasticsearch:7.11.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - playerfeedbackservice

  kib01:
    image: kibana:7.11.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - playerfeedbackservice

  player-feedback-service:
    container_name: playerfeedbackservice
    depends_on:
      - es01
    build: ./
    volumes:
      - ./src:/app
    ports:
      - 5000:5000
    networks:
      - playerfeedbackservice

volumes:
  data:
    driver: local

networks:
  playerfeedbackservice:
    driver: bridge
