version: '3.8'
services:
  es01:
    image: elasticsearch:7.11.1
    container_name: es01
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      discovery.type: single-node
    volumes:
      - es-data-elb:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - playerfeedbackservice
    restart: always

  kib01:
    image: kibana:7.11.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - playerfeedbackservice
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    volumes:
      - zookeeper-data-elb:/var/lib/zookeeper/data
      - zookeeper-log-elb:/var/lib/zookeeper/log
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - playerfeedbackservice
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - kafka-data-elb:/var/lib/kafka/data
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - playerfeedbackservice
    restart: always

volumes:
  es-data-elb:
    driver: local
    driver_opts:
      o: "size=500m"
      device: tmpfs
      type: tmpfs
  zookeeper-data-elb:
    driver: local
    driver_opts:
      o: "size=500m"
      device: tmpfs
      type: tmpfs
  zookeeper-log-elb:
    driver: local
    driver_opts:
      o: "size=500m"
      device: tmpfs
      type: tmpfs
  kafka-data-elb:
    driver: local
    driver_opts:
      o: "size=500m"
      device: tmpfs
      type: tmpfs

networks:
  playerfeedbackservice:
    driver: bridge
